=== AzizaCorp/ReVoto/packages/contracts/schemas/entidad.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "entidad.schema.json",
  "type": "object",
  "required": ["territorio", "fuente", "elecciones", "municipios"],
  "properties": {
    "territorio": {
      "$ref": "comun.schema.json#/$defs/territorio"
    },
    "fuente": {
      "type": "string",
      "minLength": 1
    },
    "elecciones": {
      "type": "array",
      "items": {
        "$ref": "comun.schema.json#/$defs/cifrasEleccion"
      }
    },
    "municipios": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["cve", "nombre"],
        "properties": {
          "cve": {
            "type": "integer",
            "minimum": 1
          },
          "nombre": {
            "type": "string"
          },
          "suprimido": {
            "type": "boolean"
          },
          "participacion": {
            "type": "object",
            "propertyNames": {
              "enum": ["2009", "2012", "2015", "2018", "2021", "2024"]
            },
            "additionalProperties": {
              "$ref": "comun.schema.json#/$defs/proporcion"
            }
          },
          "cvegeo": {
            "$ref": "comun.schema.json#/$defs/cvegeo"
          }
        },
        "additionalProperties": false
      }
    },
    "votos_esperados_por_edad": {
      "type": "object",
      "description": "W-09b: elecciones con voto esperadas (de 3: 2018, 2021, 2024) por grupo de edad.",
      "propertyNames": {
        "$ref": "comun.schema.json#/$defs/grupoEdad"
      },
      "additionalProperties": {
        "type": "number",
        "minimum": 0,
        "maximum": 3
      }
    }
  },
  "additionalProperties": false
}

=== AzizaCorp/ReVoto/apps/web/public/data/20261013-d6b23e7/entidad/15.json
{"territorio":{"nivel":"entidad","cve":15,"nombre":"México"},"fuente":"Conteos censales INE (DECEYEC)","elecciones":[{"anio":2009,"tipo":"intermedia","participacion":0.508,"lista_nominal":10020332,"por_edad":{"18-24":0.44,"25-34":0.442,"35-44":0.514,"45-59":0.591,"60+":0.593},"por_sexo":{"H":0.453,"M":0.56}},{"anio":2012,"tipo":"presidencial","participacion":0.654,"lista_nominal":10104884,"por_edad":{"18-24":0.59,"25-34":0.578,"35-44":0.666,"45-59":0.738,"60+":0.739},"por_sexo":{"H":0.598,"M":0.705}},{"anio":2015,"tipo":"intermedia","participacion":0.5,"lista_nominal":11023655,"por_edad":{"18-24":0.406,"25-34":0.397,"35-44":0.507,"45-59":0.587,"60+":0.655},"por_sexo":{"H":0.445,"M":0.551}},{"anio":2018,"tipo":"presidencial","participacion":0.671,"lista_nominal":11832204,"por_edad":{"18-24":0.605,"25-34":0.598,"35-44":0.673,"45-59":0.737,"60+":0.756},"por_sexo":{"H":0.62,"M":0.718}},{"anio":2021,"tipo":"intermedia","participacion":0.535,"lista_nominal":12376600,"por_edad":{"18-24":0.461,"25-34":0.422,"35-44":0.511,"45-59":0.615,"60+":0.683},"por_sexo":{"H":0.484,"M":0.582}},{"anio":2024,"tipo":"presidencial","participacion":0.639,"lista_nominal":13026772,"por_edad":{"18-24":0.553,"25-34":0.533,"35-44":0.609,"45-59":0.708,"60+":0.788},"por_sexo":{"H":0.581,"M":0.691}}],"votos_esperados_por_edad":{"18-24":1.619,"25-34":1.553,"35-44":1.793,"45-59":2.06,"60+":2.227},"municipios":[{"cve":1,"nombre":"Acambay de Ruíz Castañeda","cvegeo":"15001","participacion":{"2009":0.606,"2012":0.669,"2015":0.564,"2018":0.683,"2021":0.633,"2024":0.645}},{"cve":2,"nombre":"Acolman","cvegeo":"15002","participacion":{"2009":0.586,"2012":0.695,"2015":0.558,"2018":0.682,"2021":0.576,"2024":0.643}},{"cve":3,"nombre":"Aculco","cvegeo":"15003","participacion":{"2009":0.726,"2012":0.723,"2015":0.639,"2018":0.714,"2021":0.645,"2024":0.683}},{"cve":4,"nombre":"Almoloya de Alquisiras","cvegeo":"15004","participacion":{"2009":0.665,"2012":0.757,"2015":0.776,"2018":0.751,"2021":0.69,"2024":0.655}},{"cve":5,"nombre":"Almoloya de Juárez","cvegeo":"15005","participacion":{"2009":0.628,"2012":0.694,"2015":0.551,"2018":0.678,"2021":0.576,"2024":0.656}},{"cve":6,"nombre":"Almoloya del Río","cvegeo":"15006","participacion":{"2009":0.67,"2012":0.765,"2015":0.699,"2018":0.765,"2021":0.683,"2024":0.729}},{"cve":7,"nombre":"Amanalco","cvegeo":"15007","participacion":{"2009":0.659,"2012":0.75,"2015":0.743,"2018":0.765,"2021":0.722,"2024":0.692}},{"cve":8,"nombre":"Amatepec","cvegeo":"15008","participacion":{"2009":0.623,"2012":0.707,"2015":0.735,"2018":0.75,"2021":0.663,"2024":0.626}},{"cve":9,"nombre":"Amecameca","cvegeo":"15009","participacion":{"2009":0.594,"2012":0.7,"2015":0.606,"2018":0.715,"2021":0.629,"2024":0.663}},{"cve":10,"nombre":"Apaxco","cvegeo":"15010","participacion":{"2009":0.609,"2012":0.692,"2015":0.616,"2018":0.703,"2021":0.645,"2024":0.65}},{"cve":11,"nombre":"Atenco","cvegeo":"15011","participacion":{"2009":0.562,"2012":0.665,"2015":0.549,"2018":0.682,"2021":0.523,"2024":0.595}},{"cve":12,"nombre":"Atizapán","cvegeo":"15012","participacion":{"2009":0.62,"2012":0.733,"2015":0.63,"2018":0.723,"2021":0.637,"2024":0.68}},{"cve":13,"nombre":"Atizapán de Zaragoza","cvegeo":"15013","participacion":{"2009":0.446,"2012":0.635,"2015":0.438,"2018":0.663,"2021":0.515,"2024":0.651}},{"cve":14,"nombre":"Atlacomulco","cvegeo":"15014","participacion":{"2009":0.58,"2012":0.658,"2015":0.513,"2018":0.692,"2021":0.582,"2024":0.642}},{"cve":15,"nombre":"Atlautla","cvegeo":"15015","participacion":{"2009":0.563,"2012":0.666,"2015":0.638,"2018":0.714,"2021":0.652,"2024":0.671}},{"cve":16,"nombre":"Axapusco","cvegeo":"15016","participacion":{"2009":0.726,"2012":0.82,"2015":0.746,"2018":0.798,"2021":0.736,"2024":0.767}},{"cve":17,"nombre":"Ayapango","cvegeo":"15017","participacion":{"2009":0.678,"2012":0.755,"2015":0.744,"2018":0.769,"2021":0.736,"2024":0.77}},{"cve":18,"nombre":"Calimaya","cvegeo":"15018","participacion":{"2009":0.66,"2012":0.734,"2015":0.647,"2018":0.714,"2021":0.617,"2024":0.711}},{"cve":19,"nombre":"Capulhuac","cvegeo":"15019","participacion":{"2009":0.509,"2012":0.613,"2015":0.497,"2018":0.612,"2021":0.507,"2024":0.536}},{"cve":20,"nombre":"Coacalco de Berriozábal","cvegeo":"15020","participacion":{"2009":0.495,"2012":0.668,"2015":0.478,"2018":0.687,"2021":0.53,"2024":0.675}},{"cve":21,"nombre":"Coatepec Harinas","cvegeo":"15021","participacion":{"2009":0.611,"2012":0.713,"2015":0.699,"2018":0.695,"2021":0.594,"2024":0.582}},{"cve":22,"nombre":"Cocotitlán","cvegeo":"15022","participacion":{"2009":0.638,"2012":0.765,"2015":0.694,"2018":0.775,"2021":0.697,"2024":0.734}},{"cve":23,"nombre":"Coyotepec","cvegeo":"15023","participacion":{"2009":0.556,"2012":0.634,"2015":0.497,"2018":0.655,"2021":0.5,"2024":0.612}},{"cve":24,"nombre":"Cuautitlán","cvegeo":"15024","participacion":{"2009":0.53,"2012":0.672,"2015":0.497,"2018":0.696,"2021":0.529,"2024":0.663}},{"cve":25,"nombre":"Cuautitlán Izcalli","cvegeo":"15121","participacion":{"2009":0.514,"2012":0.677,"2015":0.496,"2018":0.697,"2021":0.544,"2024":0.679}},{"cve":26,"nombre":"Chalco","cvegeo":"15025","participacion":{"2009":0.504,"2012":0.615,"2015":0.438,"2018":0.623,"2021":0.446,"2024":0.57}},{"cve":27,"nombre":"Chapa de Mota","cvegeo":"15026","participacion":{"2009":0.746,"2012":0.789,"2015":0.751,"2018":0.822,"2021":0.721,"2024":0.762}},{"cve":28,"nombre":"Chapultepec","cvegeo":"15027","participacion":{"2009":0.701,"2012":0.772,"2015":0.643,"2018":0.734,"2021":0.623,"2024":0.686}},{"cve":29,"nombre":"Chiautla","cvegeo":"15028","participacion":{"2009":0.628,"2012":0.752,"2015":0.656,"2018":0.772,"2021":0.637,"2024":0.709}},{"cve":30,"nombre":"Chicoloapan","cvegeo":"15029","participacion":{"2009":0.47,"2012":0.634,"2015":0.515,"2018":0.628,"2021":0.51,"2024":0.603}},{"cve":31,"nombre":"Chiconcuac","cvegeo":"15030","participacion":{"2009":0.598,"2012":0.721,"2015":0.632,"2018":0.73,"2021":0.579,"2024":0.685}},{"cve":32,"nombre":"Chimalhuacán","cvegeo":"15031","participacion":{"2009":0.398,"2012":0.552,"2015":0.324,"2018":0.597,"2021":0.438,"2024":0.524}},{"cve":33,"nombre":"Donato Guerra","cvegeo":"15032","participacion":{"2009":0.739,"2012":0.805,"2015":0.79,"2018":0.747,"2021":0.684,"2024":0.724}},{"cve":34,"nombre":"Ecatepec de Morelos","cvegeo":"15033","participacion":{"2009":0.442,"2012":0.621,"2015":0.412,"2018":0.648,"2021":0.47,"2024":0.618}},{"cve":35,"nombre":"Ecatzingo","cvegeo":"15034","participacion":{"2009":0.678,"2012":0.722,"2015":0.709,"2018":0.773,"2021":0.769,"2024":0.747}},{"cve":36,"nombre":"Huehuetoca","cvegeo":"15035","participacion":{"2009":0.47,"2012":0.57,"2015":0.41,"2018":0.569,"2021":0.445,"2024":0.578}},{"cve":37,"nombre":"Hueypoxtla","cvegeo":"15036","participacion":{"2009":0.668,"2012":0.739,"2015":0.677,"2018":0.724,"2021":0.649,"2024":0.72}},{"cve":38,"nombre":"Huixquilucan","cvegeo":"15037","participacion":{"2009":0.547,"2012":0.677,"2015":0.537,"2018":0.726,"2021":0.643,"2024":0.696}},{"cve":39,"nombre":"Isidro Fabela","cvegeo":"15038","participacion":{"2009":0.679,"2012":0.765,"2015":0.725,"2018":0.747,"2021":0.655,"2024":0.725}},{"cve":40,"nombre":"Ixtapaluca","cvegeo":"15039","participacion":{"2009":0.475,"2012":0.623,"2015":0.464,"2018":0.644,"2021":0.476,"2024":0.59}},{"cve":41,"nombre":"Ixtapan de la Sal","cvegeo":"15040","participacion":{"2009":0.603,"2012":0.681,"2015":0.642,"2018":0.676,"2021":0.589,"2024":0.631}},{"cve":42,"nombre":"Ixtapan del Oro","cvegeo":"15041","participacion":{"2009":0.797,"2012":0.855,"2015":0.848,"2018":0.88,"2021":0.865,"2024":0.799}},{"cve":43,"nombre":"Ixtlahuaca","cvegeo":"15042","participacion":{"2009":0.571,"2012":0.661,"2015":0.516,"2018":0.694,"2021":0.619,"2024":0.69}},{"cve":44,"nombre":"Xalatlaco","cvegeo":"15043","participacion":{"2009":0.547,"2012":0.637,"2015":0.529,"2018":0.667,"2021":0.599,"2024":0.594}},{"cve":45,"nombre":"Jaltenco","cvegeo":"15044","participacion":{"2009":0.544,"2012":0.695,"2015":0.572,"2018":0.711,"2021":0.596,"2024":0.696}},{"cve":46,"nombre":"Jilotepec","cvegeo":"15045","participacion":{"2009":0.698,"2012":0.721,"2015":0.67,"2018":0.735,"2021":0.648,"2024":0.709}},{"cve":47,"nombre":"Jilotzingo","cvegeo":"15046","participacion":{"2009":0.655,"2012":0.759,"2015":0.671,"2018":0.744,"2021":0.683,"2024":0.766}},{"cve":48,"nombre":"Jiquipilco","cvegeo":"15047","participacion":{"2009":0.625,"2012":0.679,"2015":0.572,"2018":0.691,"2021":0.652,"2024":0.692}},{"cve":49,"nombre":"Jocotitlán","cvegeo":"15048","participacion":{"2009":0.632,"2012":0.719,"2015":0.608,"2018":0.755,"2021":0.679,"2024":0.709}},{"cve":50,"nombre":"Joquicingo","cvegeo":"15049","participacion":{"2009":0.643,"2012":0.753,"2015":0.742,"2018":0.776,"2021":0.724,"2024":0.752}},{"cve":51,"nombre":"Juchitepec","cvegeo":"15050","participacion":{"2009":0.608,"2012":0.711,"2015":0.629,"2018":0.738,"2021":0.667,"2024":0.724}},{"cve":52,"nombre":"Lerma","cvegeo":"15051","participacion":{"2009":0.6,"2012":0.712,"2015":0.573,"2018":0.741,"2021":0.601,"2024":0.701}},{"cve":53,"nombre":"Malinalco","cvegeo":"15052","participacion":{"2009":0.628,"2012":0.717,"2015":0.727,"2018":0.741,"2021":0.683,"2024":0.703}},{"cve":54,"nombre":"Melchor Ocampo","cvegeo":"15053","participacion":{"2009":0.582,"2012":0.668,"2015":0.535,"2018":0.68,"2021":0.582,"2024":0.663}},{"cve":55,"nombre":"Metepec","cvegeo":"15054","participacion":{"2009":0.599,"2012":0.724,"2015":0.568,"2018":0.741,"2021":0.631,"2024":0.716}},{"cve":56,"nombre":"Mexicaltzingo","cvegeo":"15055","participacion":{"2009":0.603,"2012":0.673,"2015":0.621,"2018":0.671,"2021":0.587,"2024":0.67}},{"cve":57,"nombre":"Morelos","cvegeo":"15056","participacion":{"2009":0.651,"2012":0.741,"2015":0.715,"2018":0.76,"2021":0.704,"2024":0.706}},{"cve":58,"nombre":"Naucalpan de Juárez","cvegeo":"15057","participacion":{"2009":0.451,"2012":0.632,"2015":0.446,"2018":0.645,"2021":0.492,"2024":0.641}},{"cve":59,"nombre":"Nextlalpan","cvegeo":"15059","participacion":{"2009":0.587,"2012":0.7,"2015":0.621,"
