=== AzizaCorp/ReVoto/packages/contracts/schemas/geo.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "geo.schema.json",
  "title": "Geometría TopoJSON proyectada (Lambert conforme cónica, metros): geo/entidades, geo/<cve> y geo/municipios",
  "type": "object",
  "required": ["type", "arcs", "objects", "transform"],
  "properties": {
    "type": {
      "const": "Topology"
    },
    "arcs": {
      "type": "array"
    },
    "transform": {
      "type": "object",
      "required": ["scale", "translate"],
      "properties": {
        "scale": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2
        },
        "translate": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "bbox": {
      "type": "array"
    },
    "objects": {
      "type": "object",
      "minProperties": 1,
      "maxProperties": 1,
      "additionalProperties": {
        "type": "object",
        "required": ["type", "geometries"],
        "properties": {
          "geometries": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["properties"],
              "properties": {
                "properties": {
                  "type": "object",
                  "properties": {
                    "cve": {
                      "type": "integer",
                      "minimum": 1
                    },
                    "cvegeo": {
                      "$ref": "comun.schema.json#/$defs/cvegeo"
                    },
                    "nombre": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== AzizaCorp/ReVoto/apps/web/public/data/20261013-0e071d3/geo/25.topo.json
{"type":"Topology","arcs":[[[8146,4037],[157,-120],[-1,-6],[12,-13],[18,-7],[7,-7],[7,-42],[1,-64],[66,0],[-2,-15],[23,-28],[2,-19],[18,-13],[-5,-12],[19,-18],[6,-17],[16,-7],[21,-31],[2,-17],[-6,-20],[7,-3],[-7,-15],[18,-15],[18,-1],[1,-14],[-18,-21],[3,-13],[-13,-3],[-9,-15],[5,-11],[-19,-13],[2,-9],[15,-10],[-1,-11],[8,-11],[-6,-14],[13,-4],[23,-13],[11,6],[20,-16],[18,-7],[2,-9],[15,-8],[-3,-12],[26,-8],[5,-6],[17,3],[9,-18],[15,-10],[20,-6],[24,3],[6,-5],[-3,-11],[11,-19],[-97,-74],[116,-11],[46,-25],[6,-14],[17,-13],[10,-4],[11,-13],[-4,-9],[4,-9],[13,-6],[-1,-19],[-11,-6],[-1,-25],[-12,-6],[-45,10],[-173,66],[-25,-145],[23,-46]],[[8617,2913],[-292,160],[-243,-254],[110,-92],[-150,-42],[-19,-94],[-60,32],[-15,-20],[-1,-18],[-9,-9],[-14,5],[-15,-8],[-9,2],[-14,-18],[1,-11],[-18,-10],[-10,15],[-12,-9],[-5,-19],[-13,2],[-5,-12],[-23,-10],[-7,-13],[1,-11],[-24,-7],[-5,-7],[-30,-3],[-13,8],[-22,-5],[-16,7],[-1,22],[-30,0],[-19,7],[-7,-4],[-13,21],[-11,12],[-42,23],[-20,1],[-7,-6],[-40,86],[-77,34],[-90,13],[-38,3],[-27,-19],[-113,6],[-23,-49],[7,-8],[-7,-9],[8,-34],[16,-43],[-202,-13],[-24,-140],[-31,-105],[-12,-59]],[[6882,2211],[-26,16],[-3,14],[10,9],[-7,16],[-41,33],[-14,8],[-63,48],[-13,4],[-9,21],[6,7],[-28,35],[-23,17],[-61,40],[-62,31],[-26,10],[-11,18],[-31,21],[-10,3],[-12,18],[-32,17],[-9,0],[-13,22],[17,3],[6,18],[14,-4],[7,11],[0,22],[-15,25],[-44,47],[-53,46],[-14,10],[6,5],[5,18],[-10,16],[-36,35]],[[6287,2871],[103,9],[210,15],[6,25],[-12,4],[16,65],[15,3],[-8,40],[131,83],[24,27],[17,28],[-3,9],[-45,56],[-16,3],[-17,-12],[-13,29],[-13,2],[-3,10],[14,4],[14,-17],[21,6],[12,0],[10,54],[9,24],[6,5],[9,27],[12,12],[-12,10],[6,17],[19,2],[18,18],[23,13],[-10,24],[12,4],[4,10],[-12,38],[-12,9],[-28,9],[-5,14],[-9,10],[7,13],[0,15],[-9,10],[-28,5],[16,17],[34,6],[-3,5],[18,8],[0,9],[18,3],[12,-16],[20,-2],[8,8],[-18,12],[0,16],[13,3],[14,11],[19,-10],[8,10],[-7,18],[15,7],[-3,9],[12,3],[12,10],[2,21],[7,4],[-5,13],[21,4],[17,6],[1,24]],[[6981,3802],[-18,27],[22,20],[29,-6],[11,-7],[22,-7],[21,-3],[14,-8],[28,3],[33,-7],[25,6],[23,0],[9,-4],[17,1],[7,-5],[15,19],[27,4],[10,7],[14,3],[56,-5],[1,65],[3,3],[-114,48]],[[7236,3956],[97,-31],[31,6],[72,8],[68,15],[73,13],[30,8],[10,7],[17,19],[4,16],[15,45],[6,8],[20,14],[22,11],[152,26],[187,-53],[61,-41],[45,10]],[[3467,6856],[9,-8],[20,5],[40,7],[19,-3],[22,4],[12,-7],[-8,-15],[-29,-13],[-1,-12],[-13,-22],[-20,-4],[0,-12],[25,5],[13,-6],[-6,-11],[12,-15],[-23,-1],[-2,-16],[7,-22],[13,-16],[2,-15],[-8,-7],[-19,-6],[1,-12],[20,8],[16,-12],[-7,-28],[10,-7],[-15,-28],[19,-53],[15,-27],[-20,1],[7,-30],[52,-20],[65,-4],[14,27],[28,-10],[-7,-8],[-11,3],[-9,-8],[-11,-24],[1,-11],[-12,-28],[17,-7],[75,-13],[-5,-27],[-10,2],[-14,-8],[-12,-24],[-55,-15],[14,-10],[30,-50],[33,-3],[15,4],[-5,8],[8,9],[28,-4],[9,-13],[-6,-12],[-12,-3],[-9,5],[-34,-7],[-13,-9],[40,-68],[6,-12],[-4,-15],[20,-36],[15,-1],[21,3],[24,-12],[-1,-14],[16,0],[-7,-54],[-126,4],[-32,2],[-10,-38],[-1,-16],[-5,-17],[-8,-49],[-6,3],[-24,-2],[2,9],[-22,10],[-22,18]],[[3618,5933],[-6,28],[6,7],[-17,25],[-26,63],[-11,4],[-8,-5],[-48,1],[-45,28],[-4,9],[10,10],[14,-1],[18,13],[31,6],[16,5],[-8,21],[-71,83],[3,14],[-1,37],[-18,12],[-2,26],[-6,4],[14,24],[0,16],[29,-7],[9,21],[-28,-1],[11,14],[8,21],[-1,8],[-13,12],[-16,1],[-21,-7],[-113,71],[36,18],[-11,19],[-23,0],[6,10],[-19,14],[-38,-18],[2,-10],[-12,-7],[-40,-6],[-7,-6],[-13,-35],[-44,-22],[-2,-9],[-20,6],[-20,14],[28,3],[-5,26],[-40,-18],[-3,6],[9,29],[-30,1],[19,-38],[-70,-30],[-52,-27],[0,-17],[-9,-4],[-50,-15],[-10,-1],[-8,25],[-22,-2],[-7,-25],[-19,-2],[-9,4],[-20,-1],[0,-23],[-16,7],[19,61],[-8,1],[-7,-21],[-21,7]],[[2788,6410],[3,42],[12,12],[30,-8],[21,70],[14,53],[-3,0],[12,36],[13,7],[31,8],[19,18],[82,5],[60,-18],[7,-2],[11,10],[-17,52],[-19,7],[8,26],[17,8],[-2,8],[15,6],[4,29],[-55,86],[16,7],[44,28],[26,14]],[[3137,6914],[15,-13],[17,-9],[10,6],[13,-7],[100,-1],[0,-41],[61,15],[1,22],[25,-11],[31,-20],[7,5],[15,-9],[19,-1],[16,6]],[[4904,3933],[-44,32],[-73,48],[-13,12],[-95,58],[-67,41],[-37,22],[-157,94],[-106,62],[-100,55],[-114,59],[-26,14],[-52,24],[-40,15],[-62,29],[-10,7],[4,18],[17,9]],[[3929,4532],[24,5],[-6,-10],[13,-10],[-6,-7],[12,-7],[18,18],[15,3],[9,-4],[21,-33],[20,-18],[34,-11],[26,-4],[24,-11],[16,-23],[7,-6],[51,-12],[22,-13],[35,-30],[14,-3],[40,-26],[16,-4],[21,2],[14,-10],[5,-21],[21,-23],[13,-9],[22,-1],[20,3],[49,-14],[1,-6],[22,-7],[8,-9],[0,-17],[11,-20],[20,-8],[19,7],[24,-6],[15,0],[10,-9],[17,-7],[-6,-11],[5,-13],[21,-10],[9,-9],[-2,-8],[14,-17],[10,-1],[13,11],[11,-1],[16,-15],[14,0],[1,11],[-14,6],[-12,20],[-43,28],[-37,19],[-27,24],[-21,9],[29,3],[1,-9],[17,-6],[21,-17],[27,-7],[9,-9],[21,-6],[21,2],[6,42],[-8,5],[-16,-2],[-20,-13],[-15,6],[9,13],[20,2],[22,9],[35,7],[-1,20],[5,20],[-5,21],[7,12],[12,9],[22,-1],[-2,17],[12,-2],[14,9],[13,3],[4,10],[18,5],[15,0],[41,6],[18,-7],[11,5],[-15,21],[8,10],[54,14],[11,-5],[31,13],[5,14],[15,16],[7,1],[15,-16],[37,-2],[19,-6],[3,-8],[-3,-42],[91,-78],[40,-36],[-64,-10],[11,-15],[-62,-25],[-6,-6],[6,-8],[27,-1],[-11,-33],[-16,-20],[13,-2],[15,-11],[9,13],[18,4],[16,-11],[-17,-9],[12,-11],[22,14],[8,-2],[45,19],[66,32],[17,-16],[53,-65],[3,-17],[-15,-22],[-8,-1],[-16,-14],[3,-18],[-4,-21],[-29,-14],[-16,9],[2,7],[-29,8],[-14,-9],[12,-12],[-10,-21],[-47,-34],[-18,-26],[-13,-7],[-19,-4],[3,-15],[-8,-18],[-8,-7],[-9,5],[-16,-3],[-18,8],[-5,12],[-13,3],[-3,13],[-7,9],[-14,6],[-20,-7],[-6,-24],[16,-12],[-6,-4],[-35,21],[-17,6],[-38,-4],[-22,5],[-19,8],[-39,28],[-18,5],[-17,0]],[[1954,7558],[34,-31],[-53,-14],[5,-49],[-94,-6],[-5,5],[-41,5],[-5,-9],[-32,-82],[-22,14],[-5,-6],[23,-23],[12,-19],[28,-1],[0,-13],[18,6],[18,-9],[3,-6],[-6,-24],[-4,-61],[7,-13]],[[1835,7222],[-24,-28],[-43,21],[-20,-24],[-42,21],[-19,-22],[20,-10],[-36,-43],[22,-11],[-42,-49],[-21,11],[-30,-35],[-20,10],[-17,-19],[-20,10],[-71,-84],[15,-15],[7,8],[23,-10],[29,-1],[8,11],[17,-15],[18,-9],[-2,-28],[-17,-10],[-15,-2],[-15,-17],[-4,-18],[16,-15],[1,-10],[24,-17],[-32,-13],[-16,-10],[-6,-13],[-16,7],[-6,23],[-22,10],[-4,22],[3,8],[-11,14],[-23,-3],[-6,-5],[-21,10],[-7,23],[-16,-32],[-14,-1],[-11,9],[-20,9],[-10,-9],[-13,7],[-29,-17],[-2,-16],[6,-10],[4,-19],[17,-5],[-9,-13],[5,-15],[-13,-4],[11,-10],[-22,-8],[28,-13],[18,1],[2,-9],[-12,-6],[-16,-13],[4,-10],[-8,-15],[-13,4],[-25,-15],[-7,-9],[7,-11],[-6,-8],[-29,-13],[-19,5],[-6,12],[3,25],[-16,8],[-8,-14],[-28,0],[-13,6],[0,8],[25,6],[23,19],[1,15],[-13,4],[-23,-7],[-25,19],[-26,12],[-11,-10],[-17,9],[-27,-16],[-27,-1],[-16,10],[-16,-6],[-15,-16],[5,-6],[-4,-12],[-25,-7],[-17,11],[-21,-12],[39,-40]],[[960,6666],[-15,0],[-30,24],[-22,24],[-18,12],[-23,10],[3,6],[-16,34],[-9,9],[-59,55],[-9,11]],[[762,6851],[4,4],[36,-9],[0,-21],[9,-10],[15,-6],[7,8],[-11,16],[7,2],[25,-4],[3,-13],[13,-7],[10,15],[-6,11],[-22,15],[10,4],[47,-31],[9,4],[-13,35],[14,-3],[11,-37],[10,12],[-5,5],[10,12],[32,-3],[6,20],[-38,-3],[-9,13],[-19,9],[11,5],[12,-8],[-9,33],[11,25],[17,1],[4,-20],[7,-11],[11,15],[5,-19],[13,-18],[18,7],[10,-26],[14,0],[27,22],[23,8],[6,-9],[-21,-12],[18,-8],[-8,-16],[-12,5],[-7,-9],[14,-12],[10,-16],[16,7],[17,14],[-3,12],[9,17],[12,15],[-17,11],[-6,9],[3,15],[18,17],[10,25],[1,13],[12,0],[8,-8],[23,6],[8,-9],[18,-3],[10,8],[7,15],[16,-5],[14,6],[4,13],[-1,15],[-6,11],[-2,16],[-11,39],[0,7],[-13,18],[7,22],[7,10],[19,15],[30,-6],[56,20],[19,25],[10,5],[6,15],[-13,6],[-5,14],[-23,5],[-6,12],[-18,-1],[18,-12],[6,-21],[-9,-22],[-6,-3],[-19,5],[-1,8],[-58,31],[13,16],[-20,11],[81,91],[10,15],[-16,14],[24,32],[36,-28],[-27,-38],[59,-15],[16,28],[-13,-4],[-18,14],[9,12],[1,16],[12,1],[11,14]],[[1436,7417],[18,-8],[16,47],[147,47],[13,9],[11,1],[10,19],[15,7],[3,8],[16,8],[50,-9],[9,8],[21,29],[14,4],[12,36],[-8,3],[29,19],[-6,13],[-10,4],[24,18],[134,-122]],[[3618,5933],[-6,-2],[8,-16],[-6,-4],[-39,10],[-2,-18],[-9,0],[-26,-33],[9,-5],[91,-3],[9,-20],[14,-18],[25,0],[-2,-51],[-10,0],[-6,-9],[-2,-39],[21,3],[0,14],[20,-2],[7,-16],[-6,-5],[23,-7],[25,-1],[-1,-18],[33,-44],[1,-7]],[[3789,5642],[-12,-29],[-30,-83],[-11,3],[-5,-23],[-12,2],[-10,18],[-110,0],[-13,4],[-19,-5],[-4,-11],[-17,-6],[-20,-36],[-39,-58],[-39,-18],[-4,-44],[40,-61],[8,-33],[-13,-10],[-33,-5],[-36,-73],[-92,-46]],[[3318,5128],[-49,68],[-16,2],[-24,9],[-20,10],[-12,16],[-8,33],[-29,50],[-1,4],[-36,55],[-34,53],[-52,79],[-12,14],[-27,40],[-16,30],[-36,50],[-33,37],[-41,39],[-48,38],[-24,17],[-44,27],[-51,25],[-19,20],[-18,6],[-4,8],[10,14],[15,7],[-53,97],[-64,39]],[[2572,6015],[10,18],[12,11],[11,38],[-7,11],[-22,15],[6,8],[-6,13],[34,14],[0,28],[38,22],[4,28],[-10,4],[-16,-1],[-14,4],[-1,11],[-13,12],[5,24],[15,5],[-5,14],[4,34],[15,4],[11,21],[-10,25],[40,1],[16,11],[5,13],[9,-4],[7,-12],[12,5],[25,6],[4,5],[18,-1],[0,-7],[19,-1],[0,16]],[[2611,5953],[15,-3],[1,-8],[-19,-9],[-24,20],[-3,14],[6,6],[24,-20]],[[2582,5978],[5,-4],[-9,-12],[-10,-3],[4,24],[-7,12],[13,9],[4,-26]],[[4212,5381],[24,-15],[76,-45],[87,-37],[-3,-4],[96,-38],[-9,-51],[35,-1],[2,-19],[31,-1],[-1,-17],[-29,3],[-4,-12],[35,-3],[-4,-17],[50,3],[9,-9],[23,5],[0,-14],[9,-27],[10,4],[11,-32],[58,3],[12,-6],[18,2],[3,-8],[34,-13],[31,-20],[1,-17],[8,-1],[-3,-66],[53,-9],[-1,-27],[-21,1],[-3,-31],[-19,1],[6,-25],[-95,2],[-28,-111],[-4,-4],[-3,-59],[-25,1],[-1,-38],[-25,0],[-4,-69],[13,-14],[-22,-13],[-9,-25],[1,-128],[-209,-76],[-454,247],[-58,-6]],[[3914,4545],[-14,-2],[-4,40],[-16,17],[-30,22],[-69,35],[-135,74],[-54,32],[-16,8],[-59,39],[-44,39],[-19,24],[-19,29],[-4,36],[6,47],[-3,18],[-23,34],[-14,15],[-36,33],[-36,25],[-10,11],[3,7]],[[3789,5642],[2,4],[26,-1],[-13,-27],[123,21],[32,-54],[24,-7],[20,-54],[21,-29],[14,-10],[-14,-16],[20,-11],[33,3],[30,-12],[19,1],[1,-15],[-7,-9],[40,-2],[19,-16],[1,-6],[32,-21]],[[2997,8536],[-34,-50],[12,-42],[-7,-31],[-10,-2],[-4,-27],[15,-8],[15,-30],[-11,-4],[-21,-24],[22,-36],[-114,-51],[-95,-4],[6,-35],[-72,-85],[-41,9],[-17,-20],[-30,-23],[16,-30],[-19,-30],[-38,0],[-33,17],[12,18],[-19,27],[-13,-6],[-6,19],[-24,14],[-34,-57],[-17,29],[-7,-7],[-11,15],[-13,5],[-15,-2],[-2
